[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.4.0", features = ["macros"] }